### ISSUE TITLE
no last ball for genesisunit?

### ISSUE THREAD

**Issue by foxnudt** [pmiklos/obyte-devnet#12]
![image](https://user-images.githubusercontent.com/17670742/36071464-cfa26e32-0f49-11e8-81e4-b5de6a8c4f52.png)
when i run #npm run witness, the error comes, how to solve it?

**Comment by pmiklos** [comment]
Yes, I know about that, but I am not sure what the problem is. The latest byteballcore versions don't work well with the devnet. The last version I know that works was 0.2.78. I noticed this error happens when the hub connects to the witness and tries to sync. If I just run the witness alone, it seems to run fine but as soon as the hub connects it fails. After this, restarting and reconnecting the hub results in the other error you posted, "lost units". It seems the two errors are connected.

**Comment by foxnudt** [comment]
thanks for your reply, maybe i can use 0.2.78 first and switch the byteballcore to the latest version after it works. i'll let you know if i success.

**Comment by fishera123** [comment]
@pmiklos was this commit meant to fix this issue? https://github.com/byteball/byteballcore/commit/d6f72867a942587fab5c2e9c43d339d6a85eae22

**Comment by pmiklos** [comment]
@fishera123 no, that one fixed issue #11

**Comment by fishera123** [comment]
can we ask Tony to fix this issue as well? I think its very important for byteball network to make devnet working.

**Comment by pmiklos** [comment]
upgrade to the latest devnet with the migrated Obyte libraries.
