### ISSUE TITLE
Error when npm install

### ISSUE THREAD

**Issue by luZheng-1122** [pmiklos/obyte-devnet#19]
Hi I got this error when I run npm install:
`
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v64-darwin-x64.tar.gz

node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v64-darwin-x64.tar.gz

node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v64-darwin-x64.tar.gz

node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@10.10.0 (node-v64 ABI) (falling back to source compile with node-gyp)

node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v64-darwin-x64.tar.gz

node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v64-darwin-x64.tar.gz

node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@10.10.0 (node-v64 ABI) (falling back to source compile with node-gyp)

node-pre-gyp http Connection closed while downloading tarball file

node-pre-gyp verb command build [ 'rebuild' ]
`

Any advice? Thanks in advance!

**Comment by luZheng-1122** [comment]
An update:

The above issue is led by the installation error of sqlite3@3.1.4, I solved this issue by reading this: https://github.com/mapbox/node-sqlite3/issues/612#issuecomment-227239486

Now I can successfully run `npm install` and `npm run init`.

But new issue occurs when I run: npm run genesis, the error is:
`
   app dir /Users/luzheng/Documents/BYTEBALL/byteball-devnet/witness

   not using user conf: Error: Cannot find module '/Users/luzheng/Library/Application Support/byteball-devnet-witness/conf.json'

    internal/modules/cjs/loader.js:583
    throw err;
    ^

    Error: Cannot find module '/Users/luzheng/Documents/BYTEBALL/byteball-devnet/node_modules/byteballcore/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node'

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
`

Hope someone can help, I am going to build a dev net for testing purpose.

**Comment by pmiklos** [comment]
ugh, sorry, I  missed the notifications from this repo. Not sure if you are still working on it, but I just recently updated the project and was able to build and run it. I kind of abandoned this project last year due to all kinds of errors coming from Byteball core libraries, but they seem to be resolved. At least for now. I also checked in a `package-lock.json` that might help building the project with the same dependencies I used.

**Comment by pmiklos** [comment]
I removed `package-lock.json` since it caused issues with building docker images. I also noticed you used macOS. The devnet init script works for linux, as far as I know Mac has different setup for configuration files. Your issue may be mac related too, not sure. I don't have mac so I can't test on it unfortunately. Unless someone contributes and adds support to mac the devnet is gonna be for linux only. For these reasons I am closing this issue.
